[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = { address = "4RAA1rYL3U1dFmbTTMJnu8SA1bkyJjSpWvLkZAHcjoLm", features = ["local"] }

[programs.devnet]
amm = "4RAA1rYL3U1dFmbTTMJnu8SA1bkyJjSpWvLkZAHcjoLm"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/token_metadata.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jkim/.config/solana/id.json"
